CREATE TABLE search(
 "client" varchar(13),
 "client_features_app_version_extended" varchar(65535),
 "client_features_user_agent" varchar(65535),
 "experiments" varchar(65535),
 "session_id" varchar(38),
 "session_index" int2,
 "user_id" int8,
 "visitor_id" varchar(44),
 "auto_paged" bool,
 "confirmed" bool,
 "country" varchar(64),
 "experiment_info" varchar(65535),
 "external_referrer" varchar(8192),
 "hostname" varchar(512),
 "language" varchar(7),
 "limit" int2,
 "location_accuracy" float8,
 "location_bounds_max_latitude" float8,
 "location_bounds_max_longitude" float8,
 "location_bounds_min_latitude" float8,
 "location_bounds_min_longitude" float8,
 "location_hood_search_location" varchar(65535),
 "location_latitude" float8,
 "location_location_boosts" varchar(65535),
 "location_location_filters" varchar(65535),
 "location_longitude" float8,
 "location_text" varchar(65535),
 "location_type" varchar(8),
 "offset" int2,
 "query_filters_category" varchar(65535),
 "query_filters_distance" float8,
 "query_filters_features" varchar(65535),
 "query_find_cats" varchar(65535),
 "query_find_desc" varchar(1024),
 "query_sort" varchar(15),
 "query_unfolded" bool,
 "query_features_applied" varchar(65535),
 "query_features_attempted" varchar(65535),
 "query_features_identified_phrases" varchar(65535),
 "referrer" varchar(8192),
 "relevance" varchar(25),
 "remote_ip" varchar(17),
 "request_id" varchar(16) distkey,
 "result_features_folded" bool,
 "result_features_spelling_suggestion" varchar(65535),
 "search_type" varchar(18),
 "src_request_id" varchar(18),
 "start_time" TIMESTAMP not null,
 "suggestion_prefix" varchar(4096),
 "type" varchar(8),
 "uri" varchar(8192),
 "version" int2,
 "fbuid" int8,
 "__source_filename__" varchar(4096),
 "average_precision" float8,
 "num_actions_ads" smallint,
 "num_actions_organic" smallint,
 "num_results" smallint,
 "num_views_ads" smallint,
 "num_views_organic" smallint,
 "reciprocal_rank" float8,
 "has_name_match" bool,
 "lucy_extra_folding_final_relevant_categories" varchar(65535),
 "location_parsed_accuracy" float4,
 "location_parsed_address" varchar(256),
 "location_parsed_city" varchar(256),
 "location_parsed_country" varchar(256),
 "location_parsed_zip" varchar(9),
 "num_clicked_positions" int2 not null default 0,
 "is_category_rewrite" bool,
 "num_of_search_page_ads" int2,
 "user_map_preference" varchar(25),
 "has_maxed_out_word_score" bool,
 "word_score_multiplier" float8,
 "category_id" float8,
 "query_is_attribute" float8,
 "is_internal" bool,
 "search_location_local_time" TIMESTAMP,
 "lucy_extra_rich_query" varchar(65535),
 "lucy_extra_rich_metadata" varchar(65535),
 "result_features_spelling_correction" varchar(65535),
 "num_platforms_view" smallint,
 "num_platforms_buy" smallint,
 "disable_partial_name_match" bool,
 "disable_partial_name_match_raw" bool,
 "disable_all_name_match" bool,
 "disable_all_name_match_raw" bool,
 "promoted_filters" varchar(65535),
 "is_using_promoted_filter" bool,
 "lookaside_service_type" varchar(25),
 "lookaside_mode" varchar(25),
 "lookaside_query" varchar(65535)
) SORTKEY(start_time);
CREATE TABLE search_actions(
 "index" smallint not null,
 "search_request_id" varchar(16) distkey,
 "search_start_time" TIMESTAMP not null,
 "action" varchar(15),
 "business_id" int8,
 "confirmed" bool,
 "experiment_info" varchar(65535),
 "hostname" varchar(19),
 "remote_ip" varchar(17),
 "request_id" varchar(18),
 "result_pos" int2,
 "src_request_id" varchar(18),
 "start_time" TIMESTAMP,
 "type" varchar(12),
 "uri" varchar(8192),
 "version" int2,
 "is_ad" bool
) SORTKEY(search_start_time);
CREATE TABLE search_results(
 "index" smallint not null,
 "search_request_id" varchar(16) distkey,
 "search_start_time" TIMESTAMP not null,
 "business_id" int8,
 "categories" varchar(65535),
 "distance" float8,
 "match_type" varchar(11),
 "suggested" bool
) SORTKEY(search_start_time);
CREATE TABLE search_searches(
 "index" smallint not null,
 "search_request_id" varchar(16) distkey,
 "search_start_time" TIMESTAMP not null,
 "confirmed" bool,
 "experiment_info" varchar(65535),
 "hostname" varchar(19),
 "remote_ip" varchar(17),
 "request_id" varchar(18),
 "src_request_id" varchar(18),
 "start_time" TIMESTAMP,
 "type" varchar(8),
 "uri" varchar(8192),
 "version" int2
) SORTKEY(search_start_time);
CREATE TABLE search_views(
 "index" smallint not null,
 "search_request_id" varchar(16) distkey,
 "search_start_time" TIMESTAMP not null,
 "action" varchar(6),
 "business_id" int8,
 "confirmed" bool,
 "experiment_info" varchar(65535),
 "hostname" varchar(512),
 "remote_ip" varchar(17),
 "request_id" varchar(18),
 "result_pos" int2,
 "src_request_id" varchar(18),
 "start_time" TIMESTAMP,
 "type" varchar(10),
 "uri" varchar(8192),
 "version" int2,
 "view_time" float8,
 "view_time_estimate_type" varchar(15),
 "is_ad" bool,
 "num_of_biz_page_ads" int2
) SORTKEY(search_start_time);
